version: "3.8"
services:
  recs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/home
    deploy:
      resources:
        limits:
          memory: 8g