version: "3.3"
services:
  recs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8889:8889"
    volumes:
      - .:/home
    deploy:
      resources:
        limits:
          memory: 16g
